### ISSUE TITLE
Problem with calculation after latest release

### ISSUE THREAD

**Issue by smileclaudiu** [vtex-apps/minicart-freeshipping-bar#2]
**Describe the bug**
Since the last release, the value is wrongly calculated. The 'totalizers' array sometimes contains items total, discounts and tax, but sometimes only items total and tax, without discounts, so adding the first two causes a bug.
**To Reproduce**
To reproduce you can use any products without discounts.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/47536556/108122300-bcd9ac80-70ac-11eb-91d5-dc3618bf1189.png)

**Additional context**
 Before this, using the value, everything worked fine.

**Comment by cesarocampov** [comment]
Hello @smileclaudiu, thanks for the notice.
In this use case, the taxes are cumulative or are they included on the Selling Price?
cc: @allynkalda 
Kind regards

**Comment by cesarocampov** [comment]
@smileclaudiu the fix is deployed

**Comment by smileclaudiu** [comment]
Sorry for the late response. There is a bigger problem now. There is a bug when checking shipping price and that returns NaN and for any item in the cart it displays free shipping (100% percentage).
`  const valueWithoutShipping = !getValues("Shipping") ? getValues("Shipping") : 0`
this should be
`  const valueWithoutShipping = getValues("Shipping") ? getValues("Shipping") : 0`

@cesarocampov Thank you!
