### ISSUE TITLE
It always show that you won free shipping

### ISSUE THREAD

**Issue by claudiu-iviteb** [vtex-apps/minicart-freeshipping-bar#4]
**Describe the bug**
It always says that you won free shipping regardless of the value you configured.

**To Reproduce**

Always.

**Expected behavior**
Should calculate the remaining value to add to cart, but it doesn't.

**Screenshots**

**Additional context**
The problem is with this line of code:
`const valueWithoutShipping = !getValues("Shipping") ? getValues("Shipping") : 0`
I think it should be: 
`const valueWithoutShipping = getValues("Shipping") ? getValues("Shipping") : 0`

**Comment by cesarocampov** [comment]
Hi @claudiu-iviteb , what is the account you are having troubles at?
do you have a dev workspace we can test on?

**Comment by claudiu-iviteb** [comment]
Sure: https://bugminicart--dacris.myvtex.com/
