### ISSUE TITLE
Add support for multiple Trade Policy stores with different free shipping policies

### ISSUE THREAD

**Issue by mihainutiu-vtex** [vtex-apps/minicart-freeshipping-bar#8]
**Is your feature request related to a problem? Please describe.**

Stores that use multiple trade policies (B2B stores with segmented client base) and where the free shipping policy has different values can not use the minicart-freeshipping-bar. 

**Describe the solution you'd like**

The app should be extended to include a tradepolicy challenge that should check what policy the session user is being displayed and adjust the content.

**Describe alternatives you've considered**

The clients that have multiple trade policies on the same storefront can not use the minicart-freeshipping-bar app if the value of the benefit is different.

**Additional context**

Example: The client DACRIS operates with 2 trade policies, one for B2C customers, the other for B2B customers. The B2B customers use a separate subdomain but the cart / checkout is shared on the account.
The free shipping benefit has different values for each client segment. They can not display the free-shipping bar.

**Comment by razvanudream** [comment]
This issue is addressed in this PR: https://github.com/vtex-apps/minicart-freeshipping-bar/pull/10 - please take a look and let me know if any changes are needed
